= 来自 RedGogh 的代码风格文档指南

[NOTE]
著作人：罗添胜; 笔名：RedGogh; 撰写时间：2019/08/16

首先这是一个简短的文档，描述了在项目开发中的首选代码风格。项目代码中 风格统一、简单易懂。其次我知道代码风格是因人而异的，我不太愿意把我自己的观点强加给任何人，但是在一个团队中应该保持并且遵循一定的规则。我相信我们做任何事情都需要保持这样。

== 1) 代码缩进

制表符应该由 4 个字符，也就是说每行的 `tab` 要 4 个空格。

**理由**：缩进的全部意义在于你可以一眼就能看出一个控制逻辑块的起始位置。同时也能保证代码的一致性，不同的编辑器或查看器可能对于 `tab` 的缩进宽度是不一样的。这可能会导致代码对齐效果不一致，而空格能确保在所有环境下代码对齐效果都是一致的。

缩进还有一个好处是当你函数嵌套太深的时候会给你一个警告，如果你的函数代码嵌套级数超过了三层就意味着你的函数已经很复杂了，这时候你需要考虑把它们拆分成更小的函数。

类似这样：
[source, java]
-----------------------------
public void foo() {
    for (...) {
        if (cond) {
            if (cond) {
                ...
            }
        }
    }
}
-----------------------------

可以看到上面的代码即使没有任何逻辑，看起来也是相当复杂了。所以尽量不要让你的代码缩进级数超过 3 层，如果超过了请拆分成更小的函数。因为一个人的大脑是不可能同时跟踪多个事情。

还有请不要把多个语句放在一行里面（除非你想隐藏什么东西？？？）

[source, java]
-----------------------------
if (condition) doThis();
doSomethingEverytime()
-----------------------------

== 2) 空格

在项目中空格的使用方式取决于它是函数还是关键字。所以请在以下这些关键字后面添加一个空格：

    if, switch, case, for, do, while

如果是函数，请不要加空格（以下是个反例）：

[source, java]
-----------------------------
public static void main(String[] args) {
    bytecode (0xcafebabe)
}
-----------------------------

== 3) 命名

命名这个问题我思考了很久，虽然 Java 是一门复杂且强类型的语言，但是项目在开发过程中，为了后续维护以及展示逻辑清晰的代码你的命名应该以简单为主。

=== 3.1) 变量命名

和其他 Java 项目不同，我们不需要太华丽花哨的命名，类似 `activeThreadTemporaryCounter` 这样华丽的变量命名，如果在我们团队，你应该直接命名为 `tmp`，
这样写起来更容易，并且不会让人太难以理解。

**全局变量：**虽然华丽的命名是不提倡的，但是全局变量或（和业务相关）函数还是需要一个具体的名字。称一个全局函数为 `foo()` 那么我建议你
可以直接 `/remake`。

比如你有一张 `users` 表，其中有一个 `temporaryStatus` 字段。1-表示账号正常，2-表示账号被封停你应该这样命名（前缀请具体到项目或业务模块）这是一个 `opensso`
开放授权的模块示例：

[source, java]
-----------------------------
/** 用户账号状态正常 */
int OPENSSO_USER_STATUS_NORMAL = 1;
/** 用户账号状态异常 */
int OPENSSO_USER_STATUS_STOP   = 2;
-----------------------------

=== 3.2) 函数命名

如果是公共函数，你应该尽量以简单为主。例如 `StringUtils` 其中有一个比较字符串是否相同的函数。你不应该像下面这样写（这是个反例）：

[source, java]
-----------------------------
class StringUtils {
    /** 比较两个字符串是否相等 */
    public static boolean equals(String a, String b) {
        ...
    }
}
-----------------------------

**理由**：我们说过代码风格应该尽量简单易懂，如果你函数名叫做 `equals` 那么在一个项目中会有几百上千个类都包含 `equals` 函数。所以我们只能这样使用
（指定类名并且点出函数）：

[source, java]
-----------------------------
import StringUtils;

public static void foo(String a, String b) {
    if (StringUtils.equals(a, b))
        doSomething();
}
-----------------------------

讲真的，对于我来说上面的代码不算是一个优秀的代码。并且这行代码占据了一行内很多空间，所以我们需要让命名更简单。先简单的修改一下 `StringUtils#equals`：

[source, java]
-----------------------------
class StringUtils {
    /** 比较两个字符串是否相等 */
    public static boolean streq(String a, String b) {
        ...
    }
}
-----------------------------

然后我们只需使用 `import static` 即可不需要 `StringUtils` 前缀：

[source, java]
-----------------------------
import static StringUtils.streq;

public static void foo(String a, String b) {
    if (streq(a, b))
        doSomething();
}
-----------------------------

这同样适用到类似 `OPENSSO_USER_STATUS_NORMAL` 这样的全局常量上，所以这就是为什么要变量清晰前缀的原因。

=== 3.3) 对象命名

在一个 `web` 工程中，对于 HTTP 操作来说应该只存在两种对象，`MCTL` & `VCTL`。第一个表示 Model of controller 而另一个则表示 View of controller。

请看下面这个例子：

[source, java]
-----------------------------

// 表示这是由前端传递到后端的数据接收对象
class UserProfileMCTL {
...
}

// 表示这是由后端返回给前端的数据对象
class UserProfileVCTL {
...
}

-----------------------------

而不是应该用一个 DTO 对象就代替掉所有的对象传输类！这是不合理的。

对象命名必须是具有指向性的，不能有多个涵义类似、模糊不清的命名。请勿在你的开发生涯中写出像下面这样的代码，因为这会给人造成困惑。以下是个反例：

[source, java]
-----------------------------

class User {
...
}

class UserInfo {
...
}

class UserData {
...
}

-----------------------------

首先 `User`、`UserInfo`、`UserData`，这三个类的命名含义并没有明确的指向性可以表示它主要负责的业务逻辑范围。其次如果你使用了这样的命名那么一定就表示
这三个类有很多共同之处，你应该将它们抽象出来（如果没有共同属性......？）。

如果你不知道一个类应该怎么命名，那请你们团队的大牛，让他帮你出主意！注意：这是一个很好的学习机会。

== 4) 函数/方法

在工程中（**特别是大型多人开发的工程**）函数应该简短而漂亮。这对于后来者是否能够快速融入团队上手开发是一个很关键的问题。每个函数都不应该超过 40 行。这很重要
并且 40+ 的函数应该在整个项目周期中少之又少，应该是极其**稀有**的存在。

我认为一个函数是否是合格，应该和它的复杂度和缩进级数成反比。比如你有一个业务较为复杂度函数，并且缩进大括号超过了三层，那么你就应该考虑将它拆分成更小的函数。因为
人的大脑不可能能够同时跟踪多件事情。如果你不明白缩进级数超过三层是什么意思，那么你可以看下面的示例：

[source, java]
-----------------------------
public static void pickCotton(List<Nigger> niggers) {
for (Nigger nigger : niggers) {
for (...) {
if (...) {

            }
        }
    }
}
-----------------------------

可以看到在函数内部的缩进级数刚好三层，这已经较为复杂了。请**尽量**、**尽量**、**尽量**避免级数超过三层。但是在某些情况下还是可以容忍的，这主要看你的
函数复杂度。

== 5) 注释

注释是非常重要的，但是不要过度注释，过度注释有风险。还有永远不要在你的注释里面解释代码是如何运作的：更好的做法是让别人一看你的代码就能明白它在做什么，解释
你那些 **'代码'** 简直是浪费时间。

一般来说，你的注释应该是告诉别人你的代码做了什么，而不是怎么做的。也请不要把大量注释放在函数内部，如果你的函数复杂到需要独立一份注释，你应该需要回到第四章节再
详细阅读一下。

但是这是理想情况下：通常来说业务多变，如果你觉得你目前所做的业务非常复杂，并且专业名词较多。愚蠢到（包括你自己）都不一定能看懂。那么这种情况你就需要在
函数内部注释，并解释你（包括我自己）那**自创**的 ‘狗屎’ 名词（hh。

=== 5.1) 类注释

以下是一个类的注释模板，你应该使用它来注释一个类：

[source, java]
-----------------------------
/**
* 用户服务对象类，所有针对于用户的操作都必须使用这个类的接口
* 统一管理对用户数据的增删改查管理。
*
* @author Red Gogh
  */
  public class UserService {
  ...
  }
-----------------------------

一个类的注释很简单，你只需要`简要的`解释出这个类是做什么的。它大概包含了哪些相关的功能接口即可。以及作者信息即可。

但是这里需要 **强调** 一点：即使你不是这个类的原始作者，如果你修改了这个类（哪怕是一个注释）你也需要将你的作者信息添加到类注释的结尾`@author you name`。
像下面这样：

[source, java]
-----------------------------
/**
* 用户服务对象类，所有针对于用户的操作都必须使用这个类的接口
* 统一管理对用户数据的增删改查管理。
*
* @author Red Gogh
* @author your name
  */
  public class UserService {
  ...
  }
-----------------------------

=== 5.2) 函数注释

以下是一个函数的注释模板，你应该使用它来注释函数：

[source, java]
-----------------------------
/**
* 根据用户 id 查询用户订单列表
*
* 查询用户最近一年内购买的商品列表，如果用户没有购买商品那么这个函数将会
* 返回 {@code null}.
*
* @param id
*        用户id
*
* @return 返回用户最近一年内购买的商品列表
  */
  public List<ProductOrder> findProductOrderByUserId(Long id) {
  ...
  }
-----------------------------

上面是一个注释模板，其中 `#brief` 是整个函数介绍的摘要。摘要过后是 `详细解释`，然后是参数，返回值（如果有）。这样才算得上是一个合格的函数注释。在这之前请先
记住一件事情：通常来说很多人会认为`详细解释`是不必要的，但是请你记住一件事。两周后你自己写的**垃圾代码**你都不知道它是怎么运作的，所以请你把详细注释加上。
这是必须的！

**注意**：像上面那种参数名直接命名 `id` 的情况下，你一定要确保你的代码以及注释的上下文（包括注释说明）能联系出这个 `id` 是什么意思。否则这是一个不合格的代码。像上面就可以
从 `findProductOrderByUserId` 直接联系出参数 `id` 它是一个用户的id，而不是其他什么id。

在这最后我希望你可以把这句话印在脑子里：**一个最好的注释，就是你的代码即注释。不要让过度的注释，毁掉了你原本优秀（可能？）的代码。**