= 来自 Viakko 的 Git 提交规范指南

[NOTE]
著作人：罗添胜; 笔名：Viakko; 撰写时间：2021/03/4

== 序章

这同样是一份简短的文档，它主要描述我们在多人协同工作中的一个 Git 使用和提交规范，本文档同时也包含了许多实用的 Git
使用指南以及小技巧。如果严格按照这份文档来执行代码管理，那么可以维护出一个非常帮的项目。以及提高开发效率。

在这里的序章我就先指出一个大部分人都不知道但是很实用的功能（如果你是用的图形化操作界面...那行吧，你不需要看这个。）

相信大部分人都没使用过这个命令，但是有个特别常用的需求会需要我们去使用它。那就是项目中的 `本地配置`。我相信在大部分的项目中，都需要开发人员
自己去修改本地的配置文件，比如将 Redis、MySQL 使用自己本地的服务。但是修改了配置文件后我们是不能推送到远程仓库的，所以我们可以使用以下命令
来解决这件事。

[shell]
----
git update-index --assume-unchanged <file>
----

比如，当我们的 `application-dev.yml` 文件中的一些链接信息为了本地开发修改以后，我们可以使用上面的命令禁止 Git 对该文件进行追踪管理。如下：

[shell]
----
git update-index --assume-unchanged src/resources/application-dev.yml
----

这样执行以后 git 就不会在管理这个文件了。当我们需要提交的时候，我们再执行：

[shell]
----
git update-index --no-assume-unchanged src/resources/application-dev.yml
----

这样 git 又会继续追踪这个文件的修改状态，使得你可以提交这个文件。好了，步入正题。

== 准备工作

在开始前请先执行以下配置.

**设置用户信息：** 配置你的用户名和电子邮件地址作为提交记录中的作者信息。

[shell]
----
git config --global user.name "<作者名称>"
git config --global user.email "<邮箱地址>"
----

== COMMIT

这个段落介绍我们在团队协作开发过程中，我们需要遵守哪些提交规范能够让我们更好的去管理项目以及多人协同开发工作。首先明令禁止类似 `update` 这种提交说明，这种提交是无意义的。

一个正确提交说明应该包含 `类型`、`摘要` 以及 `详细说明`，提交时请执行以下命令配置提交模板：

[shell]
----
git config commit.template ./.gitmessage
----

这样当你i提交代码的时候每开发人员都能很清晰的看到你提交了什么功能。但是通常来说我是提倡使用 `--am` 命令来提交代码，这样提交信息简短。需要注意的是，如果你想使用 `--am` 提交，那么你一定得确保，你的改动很少，基本上只涉及到一两个文件或者一两行代码的情况下才允许使用 `--am` 其他情况请老实使用 `git commit` 去编辑提交说明。